(function (lib, img, cjs) {

var p; // shortcut to reference prototypes


// symbols:



(lib.Bitmap1 = function() {
	this.initialize(img.Bitmap1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,100,101);


(lib.Bitmap10 = function() {
	this.initialize(img.Bitmap10);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,82,52);


(lib.Bitmap2 = function() {
	this.initialize(img.Bitmap2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,100,101);


(lib.Bitmap3 = function() {
	this.initialize(img.Bitmap3);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,96,237);


(lib.Bitmap4 = function() {
	this.initialize(img.Bitmap4);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,132,233);


(lib.Bitmap5 = function() {
	this.initialize(img.Bitmap5);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,77,68);


(lib.Bitmap6 = function() {
	this.initialize(img.Bitmap6);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,77,63);


(lib.Bitmap7 = function() {
	this.initialize(img.Bitmap7);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,43,31);


(lib.Bitmap8 = function() {
	this.initialize(img.Bitmap8);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,43,31);


(lib.Bitmap9 = function() {
	this.initialize(img.Bitmap9);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,43,31);

(lib.Symbol26 = function() {
	this.initialize();

	// Layer 1
	this.text = getCJSElement("TEXT",{compId:"ID_s2_txt11",width:"70",expand:"down",align:"center",class:"purpleCallOut1"});
	//this.text = new cjs.Text("ID_s2_txt11,w:68,a:c,e:d,#C1ABD1", "12px 'CiscoSans'");
	this.text.textAlign = "center";
	this.text.lineHeight = 14;
	this.text.lineWidth = 156;
	this.text.setTransform(0,0);

	this.addChild(this.text);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,159.7,38.7);


(lib.Symbol25 = function() {
	this.initialize();

	// Layer 1
	this.text = getCJSElement("TEXT",{compId:"ID_s2_txt10",width:"82",expand:"down",align:"center",class:"purpleCallOut1"});
	//this.text = new cjs.Text("ID_s2_txt10,w:68,a:c,e:d,#C1ABD1", "12px 'CiscoSans'");
	this.text.textAlign = "center";
	this.text.lineHeight = 14;
	this.text.lineWidth = 156;
	this.text.setTransform(0,0);

	this.addChild(this.text);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,159.7,38.7);


(lib.Symbol24 = function() {
	this.initialize();

	// Layer 1
	this.text = getCJSElement("TEXT",{compId:"ID_s2_txt09",width:"76",expand:"down",align:"center",class:"purpleCallOut1"});
	//this.text = new cjs.Text("ID_s2_txt09,w:68,a:c,e:d,#C1ABD1", "12px 'CiscoSans'");
	this.text.textAlign = "center";
	this.text.lineHeight = 14;
	this.text.lineWidth = 156;
	this.text.setTransform(0,0);

	this.addChild(this.text);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,159.7,38.7);


(lib.Symbol23 = function() {
	this.initialize();

	// Layer 1
	this.text = getCJSElement("TEXT",{compId:"ID_s2_txt08",width:"80",expand:"down",align:"center",class:"purpleCallOut1"});
	//this.text = new cjs.Text("ID_s2_txt08,w:68,a:c,e:d,#C1ABD1", "12px 'CiscoSans'");
	this.text.textAlign = "center";
	this.text.lineHeight = 14;
	this.text.lineWidth = 156;
	this.text.setTransform(0,0);

	this.addChild(this.text);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,159.7,38.7);


(lib.Symbol22 = function() {
	this.initialize();

	// Layer 1
	this.text = getCJSElement("TEXT",{compId:"ID_s2_txt07",width:"75",expand:"down",align:"center",class:"purpleCallOut1"});
	//this.text = new cjs.Text("ID_s2_txt07,w:75,a:c,e:d,#C1ABD1", "12px 'CiscoSans'");
	this.text.textAlign = "center";
	this.text.lineHeight = 14;
	this.text.lineWidth = 156;
	this.text.setTransform(0,0);

	this.addChild(this.text);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,159.7,38.7);


(lib.Symbol21 = function() {
	this.initialize();

	// Layer 1
	this.text = getCJSElement("TEXT",{compId:"ID_s2_txt06",width:"67",expand:"down",align:"center",class:"purpleCallOut1"});
	//this.text = new cjs.Text("ID_s2_txt06,w:67,a:c,e:d,#C1ABD1", "12px 'CiscoSans'");
	this.text.textAlign = "center";
	this.text.lineHeight = 14;
	this.text.lineWidth = 156;
	this.text.setTransform(0,0);

	this.addChild(this.text);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,159.7,38.7);


(lib.Symbol20 = function() {
	this.initialize();

	// Layer 1
	this.text = getCJSElement("TEXT",{compId:"ID_s2_txt05",width:"68",expand:"down",align:"center",class:"purpleCallOut1"});
	//this.text = new cjs.Text("ID_s2_txt05,w:68,a:c,e:d,#C1ABD1", "12px 'CiscoSans'");
	this.text.textAlign = "center";
	this.text.lineHeight = 14;
	this.text.lineWidth = 156;
	this.text.setTransform(0,0);

	this.addChild(this.text);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,159.7,38.7);


(lib.Symbol19 = function() {
	this.initialize();

	// Layer 1
	this.text = getCJSElement("TEXT",{compId:"ID_s2_txt13",width:"136",expand:"down",align:"center"});
	//this.text = new cjs.Text("ID_s2_txt13,w:143,a:c,e:d", "12px 'CiscoSans'");
	this.text.textAlign = "center";
	this.text.lineHeight = 14;
	this.text.lineWidth = 152;
	this.text.setTransform(0,0);

	this.addChild(this.text);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,156.1,20.4);


(lib.Symbol18 = function() {
	this.initialize();

	// Layer 1
	this.text = getCJSElement("TEXT",{compId:"ID_s2_txt12",width:"136",expand:"down",align:"center"});
	//this.text = new cjs.Text("ID_s2_txt12,w:136,a:c,e:d", "12px 'CiscoSans'");
	this.text.textAlign = "center";
	this.text.lineHeight = 14;
	this.text.lineWidth = 152;
	this.text.setTransform(0,0);

	this.addChild(this.text);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,156.1,20.4);


(lib.Symbol17 = function() {
	this.initialize();

	// Layer 1
	this.text = getCJSElement("TEXT",{compId:"ID_s2_txt04",width:"80",expand:"up",align:"center"});
	//this.text = new cjs.Text("ID_s2_txt04,w:80,a:c,e:u", "12px 'CiscoSans'");
	this.text.textAlign = "center";
	this.text.lineHeight = 14;
	this.text.lineWidth = 144;
	this.text.setTransform(0,0);

	this.addChild(this.text);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,148,20.4);


(lib.Symbol16 = function() {
	this.initialize();

	// Layer 1
	this.text = getCJSElement("TEXT",{compId:"ID_s2_txt03",width:"80",expand:"up",align:"center"});
	//this.text = new cjs.Text("ID_s2_txt03,w:80,a:c,e:u", "12px 'CiscoSans'");
	this.text.textAlign = "center";
	this.text.lineHeight = 14;
	this.text.lineWidth = 144;
	this.text.setTransform(0,0);

	this.addChild(this.text);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,148,20.4);


(lib.Symbol15 = function() {
	this.initialize();

	// Layer 1
	this.text = getCJSElement("TEXT",{compId:"ID_s2_txt02",width:"80",expand:"up",align:"center"});
	//this.text = new cjs.Text("ID_s2_txt02,w:80,a:c,e:u", "12px 'CiscoSans'");
	this.text.textAlign = "center";
	this.text.lineHeight = 14;
	this.text.lineWidth = 144;
	this.text.setTransform(0,0);

	this.addChild(this.text);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,148,20.4);


(lib.Symbol14 = function() {
	this.initialize();

	// Layer 1
	this.text = getCJSElement("TEXT",{compId:"ID_s2_txt01",width:"80",expand:"up",align:"center"});
	//this.text = new cjs.Text("ID_s2_txt01,w:80,a:c,e:u", "12px 'CiscoSans'");
	this.text.textAlign = "center";
	this.text.lineHeight = 14;
	this.text.lineWidth = 144;
	this.text.setTransform(0,0);

	this.addChild(this.text);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,148,20.4);


(lib.Symbol13 = function() {
	this.initialize();

	// Layer 1
	this.text = getCJSElement("TEXT",{compId:"ID_s1_txt13",width:"136",expand:"left+right",align:"center"});
	//this.text = new cjs.Text("ID_s1_txt13,w:136,a:c,e:l_r", "12px 'CiscoSans'");
	this.text.textAlign = "center";
	this.text.lineHeight = 14;
	this.text.lineWidth = 163;
	this.text.setTransform(0,0);

	this.addChild(this.text);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,167,20.4);


(lib.Symbol12 = function() {
	this.initialize();

	// Layer 1
	this.text = getCJSElement("TEXT",{compId:"ID_s1_txt12",width:"136",expand:"left+right",align:"center"});
	//this.text = new cjs.Text("ID_s1_txt12,w:136,a:c,e:l_r", "12px 'CiscoSans'");
	this.text.textAlign = "center";
	this.text.lineHeight = 14;
	this.text.lineWidth = 163;
	this.text.setTransform(0,0);

	this.addChild(this.text);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,167,20.4);


(lib.Symbol11 = function() {
	this.initialize();

	// Layer 1
	this.text = getCJSElement("TEXT",{compId:"ID_s1_txt11",width:"70",expand:"down",align:"center",class:"purpleCallOut1"});
	//this.text = new cjs.Text("ID_s1_txt11,w:70,a:c,e:d,#C1ABD1", "12px 'CiscoSans'");
	this.text.textAlign = "center";
	this.text.lineHeight = 14;
	this.text.lineWidth = 156;
	this.text.setTransform(0,0);

	this.addChild(this.text);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,159.7,38.7);


(lib.Symbol10 = function() {
	this.initialize();

	// Layer 1
	this.text = getCJSElement("TEXT",{compId:"ID_s1_txt10",width:"82",expand:"down",align:"center",class:"purpleCallOut1"});
	//this.text = new cjs.Text("ID_s1_txt10,w:82,a:c,e:d,#C1ABD1", "12px 'CiscoSans'");
	this.text.textAlign = "center";
	this.text.lineHeight = 14;
	this.text.lineWidth = 156;
	this.text.setTransform(0,0);

	this.addChild(this.text);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,159.7,38.7);


(lib.Symbol9 = function() {
	this.initialize();

	// Layer 1
	this.text = getCJSElement("TEXT",{compId:"ID_s1_txt09",width:"76",expand:"down",align:"center",class:"purpleCallOut1"});
	//this.text = new cjs.Text("ID_s1_txt09,w:76,a:c,e:d,#C1ABD1", "12px 'CiscoSans'");
	this.text.textAlign = "center";
	this.text.lineHeight = 14;
	this.text.lineWidth = 156;
	this.text.setTransform(0,0);

	this.addChild(this.text);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,159.7,38.7);


(lib.Symbol8 = function() {
	this.initialize();

	// Layer 1
	this.text = getCJSElement("TEXT",{compId:"ID_s1_txt08",width:"80",expand:"down",align:"center",class:"purpleCallOut1"});
	//this.text = new cjs.Text("ID_s1_txt08,w:80,a:c,e:d,#C1ABD1", "12px 'CiscoSans'");
	this.text.textAlign = "center";
	this.text.lineHeight = 14;
	this.text.lineWidth = 156;
	this.text.setTransform(0,0);

	this.addChild(this.text);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,159.7,38.7);


(lib.Symbol7 = function() {
	this.initialize();

	// Layer 1
	this.text = getCJSElement("TEXT",{compId:"ID_s1_txt07",width:"75",expand:"down",align:"center",class:"purpleCallOut1"});
	//this.text = new cjs.Text("ID_s1_txt07,w:75,a:c,e:d,#C1ABD1", "12px 'CiscoSans'");
	this.text.textAlign = "center";
	this.text.lineHeight = 14;
	this.text.lineWidth = 156;
	this.text.setTransform(0,0);

	this.addChild(this.text);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,159.7,38.7);


(lib.Symbol6 = function() {
	this.initialize();

	// Layer 1
	this.text = getCJSElement("TEXT",{compId:"ID_s1_txt06",width:"67",expand:"down",align:"center",class:"purpleCallOut1"});
	//this.text = new cjs.Text("ID_s1_txt06,w:67,a:c,e:d,#C1ABD1", "12px 'CiscoSans'");
	this.text.textAlign = "center";
	this.text.lineHeight = 14;
	this.text.lineWidth = 156;
	this.text.setTransform(0,0);

	this.addChild(this.text);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,159.7,38.7);


(lib.Symbol5 = function() {
	this.initialize();

	// Layer 1
	this.text = getCJSElement("TEXT",{compId:"ID_s1_txt05",width:"68",expand:"down",align:"center",class:"purpleCallOut1"});
	//this.text = new cjs.Text("ID_s1_txt05,w:68.7,a:c,e:d,#C1ABD1", "12px 'CiscoSans'");
	this.text.textAlign = "center";
	this.text.lineHeight = 14;
	this.text.lineWidth = 156;
	this.text.setTransform(0,0);

	this.addChild(this.text);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,159.7,38.7);


(lib.Symbol4 = function() {
	this.initialize();

	// Layer 1
	this.text = getCJSElement("TEXT",{compId:"ID_s1_txt04",width:"80",expand:"up",align:"center"});
	//this.text = new cjs.Text("ID_s1_txt04,w:80,a:c,e:u", "12px 'CiscoSans'");
	this.text.textAlign = "center";
	this.text.lineHeight = 14;
	this.text.lineWidth = 144;
	this.text.setTransform(0,0);

	this.addChild(this.text);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,148,20.4);


(lib.Symbol3 = function() {
	this.initialize();

	// Layer 1
	this.text = getCJSElement("TEXT",{compId:"ID_s1_txt03",width:"80",expand:"up",align:"center"});
	//this.text = new cjs.Text("ID_s1_txt03,w:80,a:c,e:u", "12px 'CiscoSans'");
	this.text.textAlign = "center";
	this.text.lineHeight = 14;
	this.text.lineWidth = 144;
	this.text.setTransform(0,0);

	this.addChild(this.text);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,148,20.4);


(lib.Symbol2 = function() {
	this.initialize();

	// Layer 1
	this.text = getCJSElement("TEXT",{compId:"ID_s1_txt02",width:"80",expand:"up",align:"center"});
	//this.text = new cjs.Text("ID_s1_txt02,w:80,a:c,e:u", "12px 'CiscoSans'");
	this.text.textAlign = "center";
	this.text.lineHeight = 14;
	this.text.lineWidth = 144;
	this.text.setTransform(0,0);

	this.addChild(this.text);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,148,20.4);


(lib.Symbol1 = function() {
	this.initialize();

	// Layer 1
	this.text = getCJSElement("TEXT",{compId:"ID_s1_txt01",width:"80",expand:"up",align:"center"});
	//this.text = new cjs.Text("ID_s1_txt01,w:80,a:c,e:u", "12px 'CiscoSans'");
	this.text.textAlign = "center";
	this.text.lineHeight = 14;
	this.text.lineWidth = 144;
	this.text.setTransform(0,0);

	this.addChild(this.text);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,148,20.4);




(lib.signalpulse = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF0000").s().p("AgtBuQAAAAgBAAQAAgBgBAAQAAAAAAAAQgBgBAAAAQAAgBgBAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQABAAAAgBQAAAAABgBQAAAAAAAAQBVg7ACgxQABgyhRgrQAAAAAAAAQgBAAAAgBQAAAAgBgBQAAAAAAgBQAAAAAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAgBAAAAQABAAAAAAQABgBAAAAQABAAAAAAQABAAAAAAQABAAAAAAQAAAAABAAQBXAvgCA4QgBA1haA+IgDABIgBAAg");
	this.shape.setTransform(4.5,24.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FF0000").s().p("AAABxQAAAAAAAAQgBAAAAgBQAAAAgBAAQAAgBAAAAQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQABAAAAAAQAAgBABAAQBTg7ADgzQAAgzhRguQgBAAAAgBQgBAAAAAAQAAgBAAAAQAAgBgBAAQAAgBAAAAQAAgBAAAAQAAAAAAgBQABAAAAgBQAAAAAAgBQABAAAAAAQABgBAAAAQAAAAABAAQAAAAABAAQAAAAABAAQAAAAABAAQAAAAABAAQBYAygDA5QgBA2hbA/IgCABIAAAAgAhZBtQgBAAAAAAQgBAAAAgBQgBAAAAAAQAAgBgBAAQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQABAAAAAAQAAgBABAAQBWg7ADgxQAAgxhSgrQgBgBAAAAQAAAAgBgBQAAAAAAAAQAAgBgBAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAgBAAAAQABAAAAgBQAAAAABAAQAAAAABgBQAAAAABAAQAAAAABAAQAAAAAAAAQABAAAAABQBYAugDA4QgBA1haA+IgCABIgBAAg");
	this.shape_1.setTransform(9,24.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FF0000").s().p("AArB4QgBAAAAAAQgBAAAAAAQgBgBAAAAQAAAAgBgBQAAAAAAgBQAAAAgBAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAgBAAAAQAAgBABAAQAAAAAAgBQBYg9ACg2QABg4hUgyQgBgBAAAAQAAAAgBgBQAAAAAAAAQAAgBAAAAQgBgBAAAAQAAgBAAAAQAAgBABAAQAAgBAAAAQAAAAABgBQAAAAAAgBQABAAAAAAQABAAAAAAQABAAAAAAQAAgBABABQAAAAABAAQAAAAABAAQBaA3gCA8QgBA6hdBBIgDABIAAAAgAgtBvQAAAAgBAAQAAAAAAAAQgBgBAAAAQAAAAgBgBQAAAAAAgBQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAAAABAAQAAgBAAAAQAAgBABAAQAAAAABgBQBTg7ACgyQABg0hQguQAAAAgBAAQAAgBAAAAQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAAAAAQAAgBABAAQAAAAABAAQAAgBABAAQAAAAAAAAQABAAAAAAQABAAAAAAQABAAAAABQBWAxgCA5QgBA2hZA/IgDABIgBAAgAiHBrQAAAAgBAAQAAAAgBAAQAAgBAAAAQgBAAAAgBQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAAAAAQAAgBABAAQAAgBABAAQBWg7ACgwQABgyhSgrQgBAAAAgBQgBAAAAAAQAAgBgBAAQAAgBAAAAQAAgBAAAAQAAAAAAgBQAAAAAAgBQAAAAAAgBQABAAAAgBQAAAAABAAQAAgBAAAAQABAAAAAAQABAAAAgBQABAAAAAAQABAAAAABQABAAAAAAQBZAvgCA3QgBA1hcA/IgDABIgBgBg");
	this.shape_2.setTransform(13.5,25);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FF0000").s().p("ABZCEQgBAAAAAAQgBAAAAgBQgBAAAAAAQgBgBAAAAQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAAAAAAAQAAgBAAAAQAAgBABAAQAAgBAAAAQABgBAAAAQBWhDACg7QABg+hUg5QAAAAgBAAQAAgBAAAAQAAgBgBAAQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQABAAAAgBQAAAAABgBQAAAAAAAAQABAAAAgBQABAAAAAAQABAAAAAAQABAAAAAAQAAAAABAAQAAAAABABQBZA8gCBDQgBA/hbBHIgDABIAAAAgAAAB2QAAAAgBAAQAAAAgBgBQAAAAAAAAQgBgBAAAAQAAgBgBAAQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAAAAAQABgBAAAAQBVg+ADg2QAAg3hTgzQgBAAAAAAQgBgBAAAAQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQABAAAAAAQAAgBAAAAQABgBAAAAQAAAAABAAQAAgBABAAQAAAAABAAQAAAAABAAQAAAAABAAQAAABABAAQBaA2gCA9QgBA6hdBBIgCABIAAAAgAhZBtQAAAAgBAAQAAAAgBgBQAAAAAAAAQgBgBAAAAQAAgBgBAAQAAgBAAAAQAAAAAAgBQAAAAAAgBQAAAAAAgBQABAAAAgBQAAAAAAAAQABgBAAAAQBWg7ACgzQABg0hSgtQAAAAgBgBQAAAAAAAAQgBgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQABAAAAgBQAAAAABAAQAAgBAAAAQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAAAQBWAygCA5QgBA2hZA/IgDABIgBAAgAizBpQAAAAgBAAQAAAAgBgBQAAAAgBAAQAAgBAAAAQgBgBAAAAQAAgBAAAAQAAAAAAgBQAAAAAAgBQAAAAAAgBQABAAAAgBQAAAAAAgBQABAAAAAAQBXg7ACgxQABgyhTgqQAAgBgBAAQAAAAAAgBQgBAAAAgBQAAAAAAAAQAAgBAAAAQgBgBABAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAAAAAgBQABAAAAAAQABgBAAAAQABAAAAAAQAAAAABAAQAAAAABAAQAAAAABABQBZAugCA4QgBA1hcA+IgDABIgBAAg");
	this.shape_3.setTransform(17.9,25.2);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FF0000").s().p("ACGCSQAAAAgBAAQAAgBgBAAQAAAAgBAAQAAgBAAAAQgBAAAAgBQAAAAAAgBQgBAAAAgBQAAAAAAAAQAAgBAAAAQABgBAAAAQAAgBAAAAQABgBAAAAQBWhLAChCQAAhFhUg/QgBAAAAAAQAAgBgBAAQAAgBAAAAQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAAAAAQABgBAAAAQABAAAAAAQABgBAAAAQABAAAAAAQABAAAAAAQAAABABAAQAAAAABAAQBZBDgBBJQgBBGhaBPIgEABIAAAAgAAsCBQgBAAAAAAQgBgBAAAAQgBAAAAAAQAAgBgBAAQAAgBAAAAQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAAAgBQAAAAABAAQAAgBAAAAQBXhDABg8QABg9hTg5QgBAAAAgBQgBAAAAAAQAAgBAAAAQgBgBAAAAQAAgBAAAAQAAgBAAAAQABgBAAAAQAAgBAAAAQABAAAAgBQAAAAABAAQAAgBAAAAQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAABQBZA8gCBCQgBBAhbBHIgDABIAAAAgAgsBzQgBAAAAgBQgBAAAAAAQgBAAAAgBQAAAAgBAAQAAgBAAAAQAAgBgBAAQAAgBAAAAQAAgBAAAAQAAAAABgBQAAAAAAgBQAAAAABgBQAAAAAAAAQBWg+ACg2QABg3hSgzQgBAAAAgBQAAAAgBAAQAAgBAAAAQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAABgBQAAAAAAgBQAAAAABgBQAAAAAAAAQABAAAAgBQABAAAAAAQABAAAAAAQABAAAAAAQAAAAABAAQAAAAABABQBYA2gCA9QgBA6hbBBIgDABIAAAAgAiGBqQAAAAgBgBQAAAAAAAAQgBAAAAgBQAAAAgBAAQAAgBAAAAQAAgBgBAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAgBAAAAQAAAAABgBQAAAAABAAQBVg8ACgyQABg0hSgtQAAgBAAAAQgBAAAAgBQAAAAgBgBQAAAAAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAgBAAAAQAAAAABgBQAAAAABAAQAAAAABAAQAAgBABAAQAAAAAAAAQABAAAAABQABAAAAAAQBZAxgDA5QgBA3hbA/IgDABIgBAAgAjgBmQAAAAgBgBQAAAAgBAAQAAAAAAgBQgBAAAAAAQAAgBAAAAQgBgBAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAgBAAAAQAAAAABgBQAAAAABAAQBWg7ACgxQABgyhSgrQgBAAAAAAQgBgBAAAAQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAAAQABgBAAAAQAAgBABAAQAAAAAAgBQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAAAQBaAvgDA4QgBA0hcA/IgDABIgBAAg");
	this.shape_4.setTransform(22.4,25.6);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FF0000").s().p("ACwCfQAAgBgBAAQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAAAQABgBAAAAQBXhTABhKQAAhMhWhFQAAgBAAAAQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABAAQAAgBAAAAQABAAAAgBQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAAAQAAAAABABQBZBJAABQQgBBNhaBXQAAAAgBAAQAAABgBAAQAAAAAAAAQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBAAAAgBQgBAAAAAAgABZCPQAAAAgBAAQAAAAgBAAQAAAAAAgBQgBAAAAAAQgBgBAAAAQAAgBAAAAQAAgBAAAAQAAAAAAgBQAAgBAAAAQAAAAAAgBQAAAAABgBQAAAAAAAAQBXhLABhDQAAhEhUg/QAAgBgBAAQAAAAAAgBQgBAAAAgBQAAAAAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAgBAAAAQAAgBABAAQAAAAAAgBQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAABQBZBCgBBJQgBBHhaBOIgDABIgBAAgAAAB+QAAAAAAAAQAAAAgBAAQAAgBgBAAQAAAAAAgBQgBAAAAgBQAAAAAAAAQAAgBAAAAQgBgBABAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAAAABgBQBUhDACg7QAAg+hTg4QgBgBAAAAQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABAAQAAgBAAAAQAAgBABAAQAAAAABAAQAAgBABAAQAAAAABAAQAAAAABAAQAAAAAAABQABAAAAAAQBZA9gBBCQgBBAhbBGIgDABIAAAAgAhZBwQgBAAAAAAQgBAAAAgBQAAAAgBAAQAAgBAAAAQgBAAAAgBQAAAAAAgBQAAAAAAgBQgBAAABAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAAAABgBQBXg9ACg2QABg4hUgyQAAgBgBAAQAAAAAAgBQgBAAAAgBQAAAAAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQABgBAAAAQAAAAABgBQAAAAAAAAQABAAAAAAQABgBAAAAQABAAAAAAQABAAAAABQABAAAAAAQBYA2gCA9QgBA6haBBIgDABIgBAAgAiyBnQgBAAAAAAQgBAAAAgBQgBAAAAAAQAAgBAAAAQgBAAAAgBQAAAAAAgBQAAAAAAgBQgBAAABgBQAAAAAAgBQAAAAAAAAQABgBAAAAQAAAAABgBQBVg7ADgyQAAg0hRguQgBAAAAgBQgBAAAAAAQAAgBAAAAQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQABAAAAgBQAAAAAAgBQABAAAAAAQAAAAABgBQAAAAABAAQAAAAABAAQAAAAABAAQAAAAABAAQAAAAABABQBYAxgDA5QgBA2hbA/IgDABIAAAAgAkMBjQgBAAAAAAQgBAAAAgBQgBAAAAAAQAAgBgBAAQAAAAAAgBQAAAAAAgBQgBAAAAgBQAAAAABgBQAAAAAAgBQAAAAAAgBQABAAAAAAQAAgBABAAQBWg7ADgwQAAgyhSgrQgBAAAAgBQAAAAgBAAQAAgBAAAAQgBgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAAAAAgBQAAAAABgBQAAAAABAAQAAAAABAAQAAgBABAAQAAAAAAAAQABAAAAAAQABABAAAAQBaAugDA4QgBA1hcA/IgCAAIgBAAg");
	this.shape_5.setTransform(26.9,25.8);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FF0000").s().p("ADdCuQAAgBgBAAQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABgBQBXhcABhSQAAhThXhKQAAgBAAAAQgBAAAAgBQAAAAAAgBQAAAAAAAAQAAgBAAgBQAAAAAAAAQAAgBAAAAQAAgBABAAQAAgBAAAAQABAAAAAAQABgBAAAAQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAABQAAAAABAAQBaBOAABXQAABVhbBgQAAABAAAAQgBAAAAABQgBAAAAAAQgBAAAAAAIgBAAIgDgBgACDCdQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAAAAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQABgBAAAAQBXhTABhKQAAhMhWhFQAAAAAAgBQgBAAAAgBQAAAAAAAAQAAgBAAgBQAAAAAAgBQAAAAAAAAQAAgBAAAAQAAgBABAAQAAgBAAAAQABAAAAAAQABgBAAAAQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAAAQAAABABAAQBZBJAABQQgBBOhaBWQAAAAgBABQAAAAgBAAQAAAAAAAAQgBAAAAABQgBgBAAAAQgBAAAAAAQgBAAAAAAQgBgBAAAAgAAsCOQAAgBgBAAQAAAAgBAAQAAAAAAgBQgBAAAAAAQgBgBAAAAQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAAAAAQBXhLABhDQAAhEhUg/QAAAAgBgBQAAAAAAAAQgBgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAgBAAAAQAAAAABgBQAAAAAAAAQABgBAAAAQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAAAQABABAAAAQBZBDgBBJQgBBGhaBOIgDACIgBAAgAgsB9QAAgBgBAAQAAAAgBAAQAAAAgBgBQAAAAAAAAQgBgBAAAAQAAgBAAAAQAAgBAAAAQgBgBABAAQAAgBAAAAQAAgBAAAAQAAAAABgBQAAAAABAAQBUhDACg8QAAg9hRg5QgBgBAAAAQAAAAgBgBQAAAAAAgBQAAAAAAAAQgBgBABAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAgBAAAAQAAAAABgBQAAAAABAAQAAAAABgBQAAAAABAAQAAAAABAAQAAABAAAAQABAAAAAAQBXA9gBBCQgBBAhZBHIgDABIgBAAgAiGBuQgBAAAAAAQgBAAAAAAQAAgBgBAAQAAAAAAgBQgBAAAAgBQAAAAAAAAQAAgBAAAAQgBgBABAAQAAgBAAAAQAAgBAAAAQAAAAABgBQAAAAABgBQBXg9ACg2QABg4hUgyQAAgBgBAAQAAAAAAgBQgBAAAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQABAAAAgBQAAAAABAAQAAgBAAAAQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAAAQBaA3gCA8QgBA6hcBBIgDACIgBgBgAjfBlQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAAAQgBgBABAAQAAgBAAAAQAAgBAAAAQABgBAAAAQAAAAABgBQBVg7ADgyQAAg0hRguQgBAAAAAAQgBgBAAAAQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQABAAAAgBQAAAAAAAAQABgBAAAAQAAAAABAAQAAgBABAAQAAAAABAAQAAAAABAAQAAAAABAAQAAAAABABQBYAxgDA5QgBA2hbA/IgDACIAAgBgAk5BiQgBgBAAAAQgBAAAAAAQgBgBAAAAQAAAAgBgBQAAAAAAgBQAAAAAAgBQgBAAAAgBQAAAAABgBQAAAAAAAAQAAgBAAAAQABgBAAAAQAAAAABgBQBWg7ADgwQAAgyhSgrQgBAAAAgBQAAAAgBAAQAAgBAAAAQgBgBAAAAQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAAAgBQAAAAABAAQAAgBABAAQAAAAABAAQAAAAABAAQAAgBAAAAQABABAAAAQABAAAAAAQBaAvgDA3QgBA1hcA/IgCABIgBAAg");
	this.shape_6.setTransform(31.4,26);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FF0000").s().p("AEKC5QAAAAgBgBQAAAAAAgBQAAAAgBAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAgBAAAAQAAgBABAAQBYhlAAhXQAAhZhYhNQAAgBgBAAQAAgBAAAAQAAgBgBAAQAAAAAAgBQAAgBAAAAQAAAAABgBQAAAAAAgBQAAAAABgBQAAAAAAAAQABgBAAAAQABAAAAAAQABAAAAAAQABAAAAAAQAAAAABAAQAAAAABAAQAAABABAAQBbBRAABdQAABbhbBnQAAABgBAAQAAABgBAAQAAAAAAAAQgBAAAAAAIgBAAIgDgBgACwCuQgBAAAAAAQAAgBAAAAQAAgBgBAAQAAAAAAgBQAAgBAAAAQAAgBABAAQAAAAAAgBQAAAAABgBQBXhdAAhRQAAhThWhLQAAAAgBAAQAAgBAAAAQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAAAgBQAAAAABgBQAAAAAAAAQABgBAAAAQAAAAABAAQAAAAABAAQAAAAABAAQAAAAABAAQAAAAABAAQAAABABAAQBaBNgBBYQAABVhaBgQAAABgBAAQAAAAgBAAQAAABAAAAQgBAAAAAAIgBAAIgDgCgABWCeQgBgBAAAAQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAgBQABAAAAgBQAAAAAAAAQAAgBABAAQBWhTABhKQAAhMhVhFQAAgBgBAAQAAAAAAgBQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAAAgBQAAAAABAAQAAgBAAAAQABgBAAAAQAAAAABAAQAAAAABAAQAAAAABAAQAAAAABAAQAAAAABAAQAAAAABABQBZBJgBBQQAABNhaBXQgBAAAAAAQAAABgBAAQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAAAAAgBQgBAAAAAAgAAACOQAAAAAAAAQAAAAgBAAQAAAAgBgBQAAAAAAgBQgBAAAAAAQAAgBAAAAQgBgBAAAAQAAgBAAAAQAAgBAAAAQABAAAAgBQAAAAAAgBQABAAAAgBQBVhKABhDQAAhEhUg/QAAgBAAAAQAAAAAAgBQAAAAAAgBQAAAAAAAAQAAgBAAgBQAAAAAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAAAAAgBQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAAAQAAAAABAAQAAAAABABQBZBCgBBJQgBBHhaBOIgDABIAAAAgAhZB9QgBAAAAAAQgBAAAAAAQgBgBAAAAQAAAAgBgBQAAAAAAgBQAAAAgBAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAgBAAAAQAAgBABAAQAAAAAAgBQBXhDABg7QABg+hTg5QgBAAAAAAQgBgBAAAAQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAgBQABAAAAgBQAAAAAAgBQABAAAAAAQAAgBABAAQAAAAAAAAQABgBAAAAQABAAAAAAQABAAAAAAQABAAAAABQABAAAAAAQBXA9gCBCQgBBAhZBGIgDABIAAAAgAizBvQgBAAAAAAQgBAAAAgBQgBAAAAAAQAAgBgBAAQAAAAAAgBQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAAAABAAQAAgBAAAAQAAgBABAAQAAAAAAgBQBYg+ACg1QABg4hUgzQgBAAAAAAQAAAAgBgBQAAAAAAgBQAAAAAAAAQgBgBAAAAQAAgBAAAAQAAgBABAAQAAgBAAAAQAAgBABAAQAAAAAAgBQABAAAAAAQABAAAAgBQABAAAAAAQABAAAAAAQAAAAABABQAAAAABAAQBaA2gCA9QgBA6hdBBIgDABIAAAAgAkNBmQAAAAgBAAQAAAAAAgBQgBAAAAAAQAAgBgBAAQAAAAAAgBQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAAAAAQAAgBABAAQAAAAABgBQBVg7ACgyQABg0hSguQAAAAAAgBQgBAAAAAAQAAgBgBAAQAAgBAAAAQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAAAgBQAAAAABAAQAAAAABgBQAAAAABAAQAAAAABAAQAAAAAAAAQABAAAAAAQABAAAAABQBZAxgDA5QgBA2hbA/IgDABIgBAAgAlnBiQAAAAgBAAQAAAAgBgBQAAAAAAAAQgBgBAAAAQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAAAgBQAAAAABAAQAAgBABAAQBWg7ACgxQABgxhSgrQgBAAAAgBQgBAAAAAAQAAgBgBAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQABAAAAgBQAAAAABgBQAAAAAAAAQABAAAAgBQABAAAAAAQABAAAAAAQABAAAAAAQABABAAAAQBaAugDA4QgBA1hcA+IgDABIgBAAg");
	this.shape_7.setTransform(35.9,25.9);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FF0000").s().p("AE3DEQgBAAAAgBQAAAAgBAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQABgBAAAAQBZhrAAhcQAAhfhZhTQAAAAAAAAQgBgBAAAAQAAgBAAAAQAAAAAAgBQAAgBAAAAQAAgBAAAAQAAAAAAgBQABAAAAgBQAAAAABAAQAAgBABAAQAAAAABAAQAAAAABAAQAAAAABAAQAAAAABAAQAAAAAAAAQABABAAAAQBdBWgBBjQAABghbBtQgBABAAAAQAAABgBAAQAAAAgBAAQAAAAgBAAIAAAAIgDgBgADdC7QgBAAAAgBQAAAAgBgBQAAAAAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQABgBAAAAQBYhlAAhXQAAhZhXhNQgBgBAAAAQAAgBgBAAQAAgBAAAAQAAAAAAgBQAAgBAAAAQAAAAAAgBQAAAAAAgBQABAAAAgBQAAAAABAAQAAgBABAAQAAAAABAAQAAAAABAAQAAAAABAAQAAAAAAAAQABAAAAAAQABABAAAAQBbBRAABdQABBbhbBnQgBABAAAAQgBABAAAAQAAAAgBAAQAAAAgBAAIAAAAIgDgBgACCCwQAAAAAAAAQgBgBAAAAQAAgBAAAAQAAAAAAgBQAAgBAAAAQAAgBAAAAQAAAAAAgBQABAAAAgBQBXhdABhRQAAhThWhLQgBAAAAAAQAAgBgBAAQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQABAAAAgBQAAAAABAAQAAgBABAAQAAAAAAAAQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAAAQABABAAAAQBaBNAABYQAABVhaBgQgBABAAAAQgBAAAAAAQAAABgBAAQAAAAgBAAIAAAAIgEgCgAAoCgQAAgBAAAAQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABAAQAAgBAAAAQBXhTABhKQAAhMhVhFQgBgBAAAAQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQABAAAAAAQAAgBABAAQAAgBAAAAQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAABQBaBJgBBQQAABNhbBXQAAAAAAAAQgBABAAAAQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBAAAAgBQAAAAgBAAgAgsCQQgBAAAAAAQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAAAgBAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAAAAAgBQABAAAAgBQAAAAABgBQBUhKABhDQABhEhTg/QAAgBAAAAQgBAAAAgBQAAAAAAgBQgBAAAAAAQAAgBAAgBQAAAAAAAAQABgBAAAAQAAgBAAAAQABgBAAAAQAAAAABgBQAAAAABAAQAAAAABAAQAAAAABAAQAAAAABAAQAAAAAAAAQABAAAAABQBYBCgCBJQAABHhZBOIgDABIAAAAgAiHB/QAAAAgBAAQAAAAgBAAQAAgBAAAAQgBAAAAgBQgBAAAAgBQAAAAAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQABgBAAAAQAAAAABgBQBWhDACg7QABg+hUg5QAAAAgBAAQAAgBAAAAQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAAAAAQABgBAAAAQAAAAABAAQAAgBABAAQAAAAABAAQAAAAABAAQAAAAABABQAAAAABAAQBZA9gCBCQgBBAhbBGIgDABIgBAAgAjhBxQAAAAgBAAQAAAAgBgBQAAAAgBAAQAAgBAAAAQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAAAQAAgBAAAAQABgBAAAAQAAAAABgBQBXg+ACg2QABg3hUgzQAAAAAAAAQgBAAAAgBQAAAAgBgBQAAAAAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAgBAAAAQAAAAABgBQAAAAABAAQAAAAABgBQAAAAABAAQAAAAAAAAQABAAAAABQABAAAAAAQBaA2gCA9QgBA6hcBBIgDABIgBAAgAk6BoQgBAAAAAAQgBAAAAgBQAAAAgBAAQAAgBAAAAQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABAAQAAgBAAAAQABAAAAgBQBWg7ACgyQABg0hSguQgBAAAAgBQAAAAgBAAQAAgBAAAAQAAgBAAAAQgBAAAAgBQAAAAAAgBQAAAAABgBQAAAAAAgBQAAAAABgBQAAAAAAAAQABAAAAgBQABAAAAAAQABAAAAAAQAAAAABAAQAAAAABAAQAAAAABABQBYAxgCA5QgCA2haA/IgDABIgBAAgAmUBkQgBAAAAAAQgBAAAAgBQAAAAgBAAQAAgBAAAAQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAAAAAQABgBAAAAQBXg7ACgxQABgxhTgrQAAAAgBgBQAAAAAAAAQgBgBAAAAQAAgBAAAAQgBgBAAAAQAAgBAAAAQAAgBAAAAQABgBAAAAQAAAAAAgBQABAAAAgBQAAAAABAAQAAAAABgBQAAAAABAAQAAAAABAAQAAAAABAAQAAABABAAQBZAugCA4QgBA1hcA+IgDABIgBAAg");
	this.shape_8.setTransform(40.5,25.7);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FF0000").s().p("AFkDRQgBgBAAAAQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAAAQAAgBABAAQCyjgiyiyQAAgBgBAAQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQABAAAAAAQABgBAAAAQAAAAABAAQAAgBABAAQAAAAABAAQAAAAABAAQAAAAABABQAAAAAAAAQABAAAAABQC5C4i4DnQgBAAAAAAQAAABgBAAQAAAAgBAAQAAABgBAAIgBAAIgCgBgAEJDGQAAAAAAAAQgBgBAAAAQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQABAAAAgBQBZhqAAhdQAAhehZhTQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAAAQABgBAAAAQAAgBABAAQAAAAAAAAQABgBAAAAQABAAAAAAQABAAAAAAQABAAAAAAQABABAAAAQABAAAAAAQBcBXAABiQAABghcBuQAAAAAAABQgBAAAAAAQAAAAgBABQAAAAgBAAIAAAAIgEgCgACvC9QAAAAAAAAQgBgBAAAAQAAgBAAAAQAAAAAAgBQAAgBAAAAQAAAAAAgBQAAAAAAgBQABAAAAgBQBYhkAAhXQAAhZhYhOQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAAAQAAgBAAAAQAAgBAAAAQABgBAAAAQAAAAABgBQAAAAAAAAQABAAAAgBQABAAAAAAQABAAAAAAQABAAAAAAQABABAAAAQABAAAAAAQBbBSAABdQAABahbBoQAAAAAAABQgBAAAAAAQgBAAAAABQgBAAAAAAIAAAAIgEgCgABVCzQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAAAQABgBAAAAQBXhdABhSQAAhThXhKQAAAAAAgBQgBAAAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQABgBAAAAQAAAAABgBQAAAAAAAAQABAAAAgBQABAAAAAAQABAAAAAAQABAAAAAAQABABAAAAQAAAAABAAQBaBOAABXQAABVhbBhQAAAAAAAAQgBABAAAAQgBAAAAAAQgBAAAAAAIAAAAIgEgBgAgDCiQAAAAgBgBQAAAAAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAAAAAgBQBVhTABhKQAAhMhUhFQAAAAAAgBQgBAAAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQABgBAAAAQAAAAABgBQAAAAAAAAQAAAAAAgBQAAAAAAAAQABAAAAAAQABAAAAAAQABAAAAABQAAAAABAAQBaBJgBBQQgBBOhaBWQAAABgBAAQAAAAAAAAQgBABAAAAQAAAAAAAAQAAAAAAAAQgBAAAAgBQgBAAAAAAQAAAAgBgBgAhaCTQAAAAgBAAQAAgBgBAAQAAAAAAAAQgBgBAAAAQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAAAQAAgBABAAQAAgBAAAAQBXhLABhDQABhEhVg/QAAAAgBAAQAAgBAAAAQAAgBgBAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAAAABgBQAAAAAAgBQAAAAABgBQAAAAABAAQAAAAAAgBQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAABQABAAAAAAQBXBDgBBJQAABGhZBOIgDACIgBAAgAi0CCQAAAAgBgBQAAAAgBAAQAAAAgBgBQAAAAAAAAQgBgBAAAAQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQABAAAAgBQAAAAABAAQBWhDACg8QAAg9hTg5QgBAAAAgBQAAAAgBAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAAAAAgBQABAAAAAAQAAgBABAAQAAAAABAAQAAAAABAAQAAAAABAAQAAAAABAAQAAAAAAAAQBZA9gBBCQgBBAhbBHIgDABIgBAAgAkOB0QgBAAAAgBQgBAAAAAAQAAAAgBgBQAAAAAAgBQgBAAAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAAAAAgBQABAAAAgBQAAAAABAAQBXg+ACg2QABg3hUgzQAAAAgBgBQAAAAAAAAQgBgBAAAAQAAgBAAAAQAAgBAAAAQAAAAAAgBQAAAAAAgBQAAAAAAgBQABAAAAgBQAAAAABAAQAAAAAAgBQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAAAQBaA3gCA8QgBA6hcBCIgDABIgBAAgAlnBrQgBAAAAgBQgBAAAAAAQAAAAgBgBQAAAAAAgBQgBAAAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQABAAAAgBQAAAAABAAQBVg8ADgyQAAg0hRguQgBAAAAAAQgBAAAAgBQAAAAAAgBQAAAAgBgBQAAAAAAAAQAAgBAAAAQAAgBAAAAQABgBAAAAQAAgBAAAAQABAAAAgBQABAAAAAAQAAAAABgBQAAAAABAAQAAAAABAAQAAAAABABQAAAAABAAQBYAxgDA5QgBA3hbA/IgDABIAAAAgAnBBnQgBAAAAgBQgBAAAAAAQgBAAAAgBQAAAAgBgBQAAAAAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQABgBAAAAQAAAAABgBQBWg6ADgxQAAgyhSgrQgBAAAAAAQAAgBgBAAQAAAAAAgBQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAAAAAQABgBAAAAQAAAAABgBQAAAAABAAQAAAAABAAQAAAAABAAQAAAAAAAAQABAAAAAAQBaAvgDA3QgBA1hcA/IgCABIgBAAg");
	this.shape_9.setTransform(45,25.5);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FF0000").s().p("AGRDeQgBgBAAAAQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAAAQAAgBAAAAQAAgBABAAQCyjtiyi/QAAgBgBAAQAAgBAAAAQAAAAAAgBQAAAAAAgBQAAgBAAAAQAAAAAAgBQAAAAABgBQAAAAAAgBQABAAAAAAQAAAAABgBQAAAAABAAQAAAAABAAQAAAAABAAQAAAAABABQAAAAABAAQAAAAAAABQC4DFi3D0QgBAAAAAAQAAABgBAAQAAAAgBAAQAAABgBAAIAAAAIgDgBgAE3DTQgBAAAAAAQAAgBgBAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAAAABgBQCyjfiyizQAAAAAAgBQgBAAAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAAAAAgBQABAAAAAAQAAgBABAAQAAAAABAAQAAAAABAAQAAAAABAAQAAAAABAAQAAAAAAABQABAAAAAAQC5C5i4DmQgBABAAAAQAAAAgBABQAAAAgBAAQAAAAgBAAIAAAAIgDgBgADcDJQAAAAAAgBQgBAAAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQABgBAAAAQBZhrAAhcQAAhfhZhTQAAAAAAAAQgBgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQABAAAAgBQAAAAABAAQAAgBAAAAQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAAAQABABAAAAQBcBWAABjQAABghcBtQAAABAAAAQgBAAAAABQAAAAgBAAQAAAAgBAAIAAAAIgEgBgACCDAQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAAAQAAgBAAAAQAAgBAAAAQABgBAAAAQBYhlAAhXQAAhZhYhOQAAAAAAAAQgBgBAAAAQAAgBAAAAQAAAAAAgBQAAgBAAAAQAAAAAAgBQAAAAAAgBQABAAAAgBQAAAAABAAQAAgBAAAAQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAAAQABABAAAAQBbBRAABdQAABbhbBnQAAABAAAAQgBAAAAABQgBAAAAAAQgBAAAAAAIAAAAIgEgBgAAoC1QAAAAAAAAQgBgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQABAAAAgBQBXhdABhRQAAhThXhLQAAAAAAAAQgBgBAAAAQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQABAAAAgBQAAAAABAAQAAgBAAAAQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAAAQAAABABAAQBaBNAABYQAABVhbBgQAAABAAAAQgBAAAAAAQgBABAAAAQgBAAAAAAIAAAAIgEgCgAgwClQAAgBAAAAQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAAAAAQBVhTABhLQAAhLhUhFQAAgBAAAAQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQABAAAAgBQAAAAABAAQAAgBAAAAQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAAAQAAAAABABQBYBJgBBPQgBBOhYBXQAAAAgBAAQAAABAAAAQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBAAAAgBQAAAAgBAAgAiHCVQAAAAgBAAQAAAAgBAAQAAgBAAAAQgBAAAAgBQAAAAgBAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAAAABgBQAAAAAAgBQBXhKABhDQABhEhVg/QAAgBgBAAQAAAAAAgBQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAAAAAAAQAAgBABAAQAAgBAAAAQAAgBABAAQAAAAABgBQAAAAAAAAQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAABQBZBCgBBJQAABHhbBOIgDABIgBAAgAjhCEQAAAAgBAAQAAAAgBAAQAAgBgBAAQAAAAAAgBQgBAAAAgBQAAAAAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQABgBAAAAQAAAAABgBQBWhDACg7QAAg+hTg5QgBAAAAAAQAAgBgBAAQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAAAAAQABgBAAAAQAAAAABAAQAAgBABAAQAAAAABAAQAAAAABAAQAAAAABABQAAAAAAAAQBZA9gBBCQgBBAhbBGIgDABIgBAAgAk7B2QgBAAAAAAQgBAAAAgBQAAAAgBAAQAAgBAAAAQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAAAQAAgBAAAAQABgBAAAAQAAAAABgBQBXg+ACg2QABg3hUgzQAAAAgBAAQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQABgBAAAAQAAAAABgBQAAAAAAAAQABAAAAgBQABAAAAAAQABAAAAAAQABAAAAABQABAAAAAAQBaA2gCA9QgBA6hcBBIgDABIgBAAgAmUBtQgBAAAAAAQgBAAAAgBQAAAAgBAAQAAgBAAAAQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAAAQABgBAAAAQAAgBABAAQBVg7ADgzQAAgzhRguQgBAAAAgBQAAAAgBAAQAAgBAAAAQAAgBgBAAQAAgBAAAAQAAAAAAgBQAAAAAAgBQABAAAAgBQAAAAAAgBQABAAAAAAQABAAAAgBQAAAAABAAQAAAAABAAQAAAAABAAQAAAAABAAQAAAAABAAQBYAygDA5QgBA2hbA/IgDABIAAAAgAnuBpQgBAAAAAAQgBAAAAgBQgBAAAAAAQAAgBgBAAQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQABAAAAAAQAAgBABAAQBWg7ADgxQAAgxhSgrQgBgBAAAAQAAAAgBgBQAAAAAAAAQAAgBgBAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAAAAAgBQABAAAAgBQAAAAABAAQAAAAABgBQAAAAABAAQAAAAABAAQAAAAAAAAQABABAAAAQBaAugDA4QgBA1hcA+IgCABIgBAAg");
	this.shape_10.setTransform(49.5,25.2);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FF0000").s().p("AG9DpQAAgBgBAAQAAAAAAgBQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAAAAAAAQAAgBABAAQAAgBAAAAQC1j2i1jNQAAAAAAAAQAAgBgBAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQABgBAAAAQAAAAAAgBQABAAAAgBQAAAAABAAQAAAAABgBQAAAAAAAAQABAAAAAAQABAAAAAAQABABAAAAQABAAAAAAQABABAAAAQC6DSi6D9QAAAAAAAAQgBABAAAAQgBAAAAAAQgBABAAAAIgBAAIgDgBgAFjDgQAAAAgBAAQAAgBAAAAQAAgBgBAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAAAABgBQAAAAAAgBQCzjsizjAQAAAAAAgBQAAAAgBgBQAAAAAAAAQAAgBAAgBQAAAAAAgBQAAAAABAAQAAgBAAAAQAAgBABAAQAAAAABgBQAAAAAAAAQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAABQABAAAAAAQC4DGi4DzQAAABAAAAQgBAAAAABQgBAAAAAAQgBAAAAAAIgBAAIgDgBgAEJDWQAAgBgBAAQAAAAAAgBQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABAAQAAgBAAAAQCyjgixiyQgBgBAAAAQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAAAgBQAAAAABAAQAAgBAAAAQABAAAAAAQABgBAAAAQABAAAAAAQABAAAAAAQABAAAAABQABAAAAAAQAAAAABABQC4C4i4DnQAAAAgBAAQAAABAAAAQgBAAAAAAQgBABAAAAIgBAAIgDgBgACvDLQAAAAgBAAQAAgBAAAAQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQABAAAAgBQAAAAAAgBQBahqAAhdQgBhehYhTQgBAAAAgBQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQABAAAAAAQAAgBAAAAQABgBAAAAQABAAAAAAQAAgBABAAQAAAAABAAQAAAAABAAQAAAAABAAQAAABABAAQAAAAABAAQBcBXAABiQAABghcBuQAAAAgBABQAAAAAAAAQgBAAAAABQgBAAAAAAIgBAAIgDgCgABVDCQAAAAgBAAQAAgBAAAAQAAgBgBAAQAAAAAAgBQAAgBAAAAQAAAAAAgBQABAAAAgBQAAAAAAgBQBYhkABhXQAAhZhYhOQAAAAgBgBQAAAAAAgBQAAAAgBgBQAAAAAAgBQAAAAAAAAQAAgBAAAAQABgBAAAAQAAgBAAAAQABAAAAgBQABAAAAAAQAAAAABgBQAAAAABAAQAAAAABAAQAAAAABAAQAAABABAAQAAAAAAAAQBcBSAABdQAABahbBoQAAAAgBABQAAAAgBAAQAAAAgBABQAAAAgBAAIAAAAIgDgCgAgDC4QgBAAAAgBQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQABAAAAAAQAAgBAAAAQBWhdAAhUQAAhRhUhKQAAAAgBgBQAAAAAAAAQAAgBgBAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQABgBAAAAQAAgBAAAAQABAAAAgBQAAAAABAAQAAAAABgBQAAAAAAAAQAAAAAAAAQAAAAABAAQAAABABAAQAAAAAAAAQBbBOgBBVQAABXhaBhQAAAAgBAAQAAABgBAAQAAAAAAAAQAAAAAAAAIAAAAIgDgBgAhdCnQgBAAAAgBQAAAAAAAAQgBgBAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAgBAAAAQAAAAABgBQBWhTABhMQAAhKhVhFQAAAAgBgBQAAAAAAAAQAAgBgBAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQABgBAAAAQAAgBAAAAQABAAAAgBQAAAAABAAQAAAAABgBQAAAAABAAQAAAAABAAQAAAAABAAQAAAAABABQAAAAAAAAQBYBJgBBOQAABQhYBWQgBABAAAAQAAAAgBAAQAAABgBAAQAAAAgBAAQAAAAgBAAQAAAAgBgBQAAAAgBAAQAAAAAAgBgAi0CYQgBAAAAAAQgBgBAAAAQAAAAgBAAQAAgBgBAAQAAAAAAgBQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQABAAAAAAQAAgBAAAAQABgBAAAAQBWhLAChEQAAhDhUg/QgBAAAAAAQAAgBgBAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAAAAAgBQAAAAABgBQAAAAAAgBQABAAAAAAQABAAAAgBQAAAAABAAQAAAAABAAQAAAAABAAQAAAAABABQAAAAABAAQBZBDgBBHQgBBIhbBOIgDACIAAAAgAkOCHQgBAAAAgBQgBAAAAAAQgBAAAAgBQAAAAgBAAQAAgBAAAAQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQABAAAAgBQAAAAAAgBQABAAAAAAQBXhDABg8QABg9hUg5QAAAAAAgBQgBAAAAAAQAAgBAAAAQgBgBAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAgBAAAAQAAAAABgBQAAAAAAAAQABgBAAAAQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAAAQBZA9gCBCQgBBAhbBHIgDABIAAAAgAlpB5QAAAAgBgBQAAAAAAAAQgBAAAAgBQAAAAgBgBQAAAAAAAAQgBgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQABAAAAgBQAAAAAAgBQABAAAAAAQBYg+ACg2QABg3hUgzQgBAAAAgBQAAAAgBAAQAAgBAAAAQAAgBgBAAQAAgBAAAAQAAAAAAgBQAAAAABgBQAAAAAAgBQAAAAABgBQAAAAAAAAQABAAAAgBQAAAAABAAQAAAAABAAQAAAAABAAQAAAAABAAQAAAAABAAQBaA3gCA8QgBA6hdBCIgDABIgBAAgAnCBwQAAAAgBgBQAAAAgBAAQAAAAAAgBQgBAAAAgBQAAAAAAAAQgBgBAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAgBAAAAQAAAAABgBQAAAAAAAAQBWg8ACgyQABg0hSguQAAAAgBAAQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQABgBAAAAQAAAAABgBQAAAAABAAQAAAAAAgBQABAAAAAAQABAAAAAAQABAAAAABQABAAAAAAQBYAxgCA5QgBA3hbA/IgDABIgBAAgAocBsQAAAAgBgBQAAAAgBAAQAAAAAAgBQgBAAAAgBQAAAAgBAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAgBAAAAQAAgBABAAQAAAAAAgBQBXg6ACgxQABgyhTgrQAAAAAAAAQgBgBAAAAQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABAAQAAgBAAAAQABAAAAgBQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAAAQAAAAABAAQBZAvgCA3QgBA1hcA/IgDABIgBAAg");
	this.shape_11.setTransform(54,25);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FF0000").s().p("AHrDzQgBAAAAAAQgBgBAAAAQAAgBAAAAQgBgBAAAAQAAgBAAAAQAAgBAAAAQAAAAABgBQAAAAAAgBQC1j+i0jZQgBAAAAgBQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAgBQABAAAAgBQAAAAAAAAQABgBAAAAQAAAAABgBQAAAAABAAQAAAAABAAQAAAAABAAQAAAAABAAQAAAAABAAQAAAAAAABQABAAAAAAQC6Dfi6EFQAAABAAAAQgBAAAAABQgBAAAAAAQAAAAgBAAIgBAAIgCgBgAGQDrQAAgBAAAAQgBAAAAgBQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAAAAAAAQAAgBABAAQAAgBAAAAQC1j2i0jNQgBAAAAAAQAAgBAAAAQgBgBAAAAQAAgBAAAAQAAgBAAAAQABgBAAAAQAAAAAAgBQABAAAAgBQAAAAABAAQAAAAABgBQAAAAABAAQAAAAABAAQAAAAABAAQAAABAAAAQABAAAAAAQABABAAAAQC6DSi6D9QAAAAAAAAQgBABAAAAQgBAAAAAAQAAABgBAAIgBAAIgDgBgAE2DiQAAAAAAAAQgBgBAAAAQAAgBgBAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAAAABgBQAAAAAAgBQCzjsiyjAQgBAAAAgBQAAAAAAgBQgBAAAAAAQAAgBAAgBQAAAAAAgBQAAAAABAAQAAgBAAAAQAAgBABAAQAAAAABgBQAAAAAAAAQABAAAAAAQABAAABAAQAAAAABAAQAAAAAAAAQABAAAAABQABAAAAAAQC4DGi4DzQAAABAAAAQgBAAAAABQgBAAAAAAQAAAAgBAAIgBAAIgDgBgADcDYQAAgBgBAAQAAAAAAgBQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABAAQAAgBAAAAQCyjgixiyQgBgBAAAAQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAAAgBQAAAAABAAQAAgBABAAQAAAAAAAAQABgBAAAAQABAAAAAAQABAAAAAAQABAAAAABQABAAAAAAQAAAAABABQC4C4i4DnQAAAAAAAAQgBABAAAAQgBAAAAAAQgBABAAAAIgBAAIgDgBgACCDNQAAAAgBAAQAAgBAAAAQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAAAgBQAAAAABgBQBZhqAAhdQAAhehZhTQgBAAAAgBQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAAAAAQAAgBABAAQAAgBAAAAQABAAAAAAQABgBAAAAQAAAAABAAQABAAAAAAQABAAAAAAQAAABABAAQAAAAABAAQBcBXAABiQAABghcBuQAAAAgBABQAAAAAAAAQgBAAAAABQgBAAAAAAIgBAAIgDgCgAAoDEQAAAAgBAAQAAgBAAAAQAAgBgBAAQAAAAAAgBQAAgBAAAAQAAAAABgBQAAAAAAgBQAAAAABgBQBYhkAAhZQAAhXhYhOQAAAAgBgBQAAAAAAgBQAAAAgBgBQAAAAAAgBQAAAAAAAAQAAgBABAAQAAgBAAAAQAAgBABAAQAAAAAAgBQABAAAAAAQABAAAAgBQAAAAABAAQABAAAAAAQAAAAABAAQAAABABAAQAAAAABAAQBbBSAABbQAABchbBoQAAAAgBABQAAAAgBAAQAAAAAAABQgBAAAAAAIgBAAIgDgCgAgwC6QgBAAAAgBQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAAAAAQAAgBABAAQBVhdAAhUQAAhRhUhKQAAAAgBgBQAAAAAAAAQAAgBgBAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAgBAAAAQAAgBABAAQAAAAAAgBQABAAAAAAQAAAAABgBQAAAAABAAQAAAAABAAQAAAAABAAQAAABABAAQAAAAABAAQBYBOgBBVQAABXhYBhQAAAAgBAAQAAABgBAAQAAAAAAAAQgBAAAAAAIgBAAIgDgBgAiKCpQgBAAAAgBQAAAAAAAAQgBgBAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAgBAAAAQAAAAABgBQBWhTABhMQAAhKhVhFQAAAAgBgBQAAAAAAAAQAAgBgBAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQABgBAAAAQAAgBABAAQAAAAAAgBQABAAAAAAQAAAAABgBQAAAAABAAQAAAAABAAQAAAAABAAQAAAAABABQAAAAABAAQBZBJgBBOQAABQhaBWQgBABAAAAQAAAAgBAAQAAABgBAAQAAAAgBAAQAAAAgBAAQAAAAgBgBQAAAAAAAAQgBAAAAgBgAjhCaQgBAAAAAAQAAgBgBAAQAAAAgBAAQAAgBAAAAQgBAAAAgBQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAgBQABAAAAAAQAAgBAAAAQABgBAAAAQBWhLAChFQAAhChUg/QgBAAAAAAQAAgBgBAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAAAAAgBQAAAAABgBQAAAAAAgBQABAAAAAAQABAAAAgBQAAAAABAAQABAAAAAAQABAAAAAAQAAAAABABQAAAAABAAQBZBDgBBHQgBBIhaBOIgEACIAAAAgAk7CJQgBAAAAgBQgBAAAAAAQgBAAAAgBQAAAAgBAAQAAgBAAAAQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQABAAAAgBQAAAAAAgBQABAAAAAAQBXhDABg9QABg8hTg5QgBAAAAgBQgBAAAAAAQAAgBAAAAQgBgBAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAgBAAAAQABAAAAgBQAAAAABAAQAAgBAAAAQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAAAQBZA9gCBBQgBBBhbBHIgDABIAAAAgAmVB7QgBAAAAgBQgBAAAAAAQgBAAAAgBQAAAAgBgBQAAAAAAAAQgBgBAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAAAAAgBQAAAAABgBQAAAAAAAAQBYg+ACg2QABg3hUgzQgBAAAAgBQAAAAgBAAQAAgBAAAAQAAgBAAAAQgBgBAAAAQAAAAAAgBQAAAAABgBQAAAAAAgBQAAAAABgBQAAAAAAAAQABAAAAgBQABAAAAAAQABAAAAAAQAAAAABAAQAAAAABAAQAAAAABAAQBaA3gCA8QgBA6hdBCIgDABIAAAAgAnvByQAAAAgBgBQAAAAAAAAQgBAAAAgBQAAAAgBgBQAAAAAAAAQgBgBAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAgBAAAAQAAAAABgBQAAAAABAAQBVg8ACgyQABg0hSguQAAAAgBAAQAAAAAAgBQAAAAgBgBQAAAAAAgBQAAAAAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAgBAAAAQAAAAABgBQAAAAABAAQAAAAABgBQAAAAAAAAQABAAAAAAQABAAAAABQABAAAAAAQBYAxgCA5QgBA3hbA/IgDABIgBAAgApJBuQAAAAgBgBQAAAAgBAAQAAAAAAgBQgBAAAAgBQAAAAAAAAQgBgBAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAgBAAAAQAAgBABAAQAAAAABgBQBWg6ACgxQABgyhSgrQgBAAAAAAQgBgBAAAAQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQABAAAAAAQAAgBABAAQAAAAAAgBQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAAAQBZAvgCA3QgBA1hcA/IgDABIgBAAg");
	this.shape_12.setTransform(58.5,24.8);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FF0000").s().p("AIXD6QAAAAAAgBQgBAAAAAAQAAgBAAAAQgBgBAAAAQAAgBAAAAQAAAAAAgBQAAAAABgBQAAAAAAgBQC1kDi1jiQAAAAAAgBQgBAAAAgBQAAAAAAAAQAAgBAAgBQAAAAAAgBQABAAAAAAQAAgBAAAAQABgBAAAAQABAAAAgBQAAAAABAAQAAAAABAAQAAAAABAAQAAAAABAAQAAAAABABQAAAAAAAAQABABAAAAQC6Dni6EKQAAAAAAABQgBAAAAAAQAAAAgBABQAAAAgBAAIgBAAIgDgBgAG9D0QAAAAAAAAQgBgBAAAAQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAAAgBQC1j+i1jZQAAAAAAgBQAAAAgBgBQAAAAAAAAQAAgBAAgBQAAAAAAAAQABgBAAAAQAAgBAAAAQABAAAAgBQAAAAABAAQAAgBABAAQAAAAABAAQAAAAABAAQAAAAABAAQAAAAABABQAAAAAAAAQABAAAAABQC6Dfi6EEQAAABAAAAQgBABAAAAQgBAAAAAAQgBAAAAAAIgBABIgDgCgAFjDsQAAAAgBgBQAAAAAAAAQAAgBgBAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAgBAAAAQC1j2i1jMQAAgBAAAAQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQABAAAAgBQAAAAAAgBQABAAAAAAQAAgBABAAQAAAAABAAQAAAAABAAQAAgBAAAAQABABAAAAQABAAAAAAQABAAAAABQABAAAAAAQC6DTi6D8QAAAAAAABQgBAAAAAAQgBABAAAAQgBAAAAAAIgBAAIgDgBgAEJDjQAAAAgBAAQAAgBAAAAQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAAAgBQCzjsizi/QAAgBAAAAQAAgBgBAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAgBAAAAQAAAAABgBQAAAAABAAQAAgBAAAAQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAAAQABABAAAAQABAAAAAAQC4DGi4DzQAAABAAAAQgBABAAAAQgBAAAAAAQgBAAAAAAIgBABIgDgCgACvDZQAAAAgBgBQAAAAAAgBQAAAAgBAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAgBAAAAQCyjfixizQgBAAAAgBQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAAAQAAgBABAAQAAgBAAAAQAAgBABAAQAAAAAAgBQABAAAAAAQABAAAAAAQABAAAAgBQABABAAAAQABAAAAAAQABAAAAAAQAAABABAAQC4C4i4DnQAAAAgBABQAAAAAAAAQgBABAAAAQgBAAAAAAIgBAAIgDgBgABVDPQAAgBgBAAQAAAAAAgBQAAAAgBgBQAAAAAAAAQAAgBAAgBQAAAAAAAAQABgBAAAAQAAgBAAAAQBahrAAhdQgBhehYhTQgBAAAAgBQAAAAAAAAQgBgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQABgBAAAAQAAgBAAAAQABAAAAgBQABAAAAAAQABAAAAAAQAAAAABgBQABAAAAABQABAAAAAAQAAAAABAAQAAAAABABQBcBWAABiQAABghcBuQAAABgBAAQAAAAAAAAQgBABAAAAQgBAAAAAAIgBAAIgDgBgAgDDGQAAgBgBAAQAAAAAAgBQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQABAAAAAAQAAgBAAAAQBWhlABhZQAAhXhWhOQAAAAgBgBQAAAAAAAAQAAgBgBAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQABgBAAAAQAAAAAAgBQABAAAAAAQABgBAAAAQAAAAABAAQAAAAABAAQAAgBAAABQAAAAAAAAQAAAAABAAQAAAAAAABQBcBRAABbQAABchbBoQAAABgBAAQAAAAgBAAQAAABAAAAQAAAAAAAAIAAAAIgDgBgAhdC7QgBAAAAgBQAAAAAAAAQgBgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQABgBAAAAQAAgBAAAAQBYhdAAhUQAAhRhWhKQAAAAgBAAQAAgBAAAAQAAgBgBAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQABAAAAgBQAAAAAAgBQABAAAAAAQABgBAAAAQAAAAABAAQAAAAABgBQAAAAABABQAAAAABAAQAAAAABAAQAAAAAAABQBZBNgBBVQAABXhYBhQAAAAgBABQAAAAgBAAQAAAAgBAAQAAAAgBAAIAAABIgDgCgAi3CqQgBAAAAAAQAAgBAAAAQgBgBAAAAQAAAAAAgBQAAgBAAAAQAAAAABgBQAAAAAAgBQAAAAABgBQBWhTABhMQAAhJhVhGQAAAAgBAAQAAgBAAAAQAAgBgBAAQAAAAAAgBQAAgBAAAAQAAgBAAAAQABAAAAgBQAAAAAAgBQABAAAAAAQABgBAAAAQAAAAABAAQAAAAABgBQAAAAABAAQAAAAABABQAAAAABAAQAAAAAAAAQBaBJgBBOQAABQhaBWQgBABAAAAQAAAAgBABQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAgBgBAAQAAAAAAgBgAkOCbQgBAAAAAAQgBAAAAgBQAAAAgBAAQAAAAgBgBQAAAAAAgBQAAAAgBAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQABgBAAAAQAAgBAAAAQABAAAAgBQBWhKAChFQAAhDhUg+QgBgBAAAAQAAgBgBAAQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAAAAAQABgBAAAAQABAAAAAAQAAAAABAAQAAgBABAAQAAAAABABQAAAAABAAQAAAAABABQBZBCgBBHQgBBIhbBPIgDABIAAAAgAloCKQgBAAAAAAQgBAAAAgBQgBAAAAAAQAAgBgBAAQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAAAQAAgBAAgBQABAAAAAAQAAgBAAAAQABgBAAAAQBXhDABg+QABg7hUg5QAAAAAAAAQgBgBAAAAQAAgBAAAAQgBAAAAgBQAAgBAAAAQAAAAAAgBQAAAAABgBQAAAAAAgBQAAAAABgBQAAAAABAAQAAAAAAgBQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAABQBZA8gCBAQgBBChbBHIgDABIAAAAgAnDB8QAAAAAAAAQgBgBAAAAQgBAAAAAAQAAgBgBAAQAAgBAAAAQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQABAAAAgBQAAAAAAAAQABgBAAAAQBYg+ACg2QABg3hUgzQgBAAAAAAQAAgBgBAAQAAAAAAgBQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAAAgBQAAAAABAAQAAgBAAAAQABAAAAAAQAAgBABAAQAAAAABAAQAAAAABAAQAAAAABAAQAAAAABABQBaA2gCA9QgBA6hdBBIgDABIgBAAgAocBzQAAAAgBAAQAAgBAAAAQgBAAAAAAQgBgBAAAAQAAgBAAAAQgBgBAAAAQAAgBAAAAQAAAAAAgBQAAAAABgBQAAAAAAgBQAAAAABAAQAAgBAAAAQBWg7ACgzQABg0hSgtQAAgBgBAAQAAAAAAgBQAAAAgBAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQABAAAAgBQAAAAABAAQAAgBABAAQAAAAAAAAQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAAAQBYAygCA4QgBA3hbA/IgDABIgBAAgAp2BvQAAAAgBAAQAAgBgBAAQAAAAAAAAQgBgBAAAAQAAgBgBAAQAAgBAAAAQAAgBAAAAQAAAAAAgBQAAgBABAAQAAAAAAgBQAAAAABgBQAAAAAAAAQBXg7ACgxQABgyhTgqQAAgBAAAAQgBAAAAgBQAAAAgBgBQAAAAAAgBQAAAAAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAAAAAgBQABAAAAAAQABgBAAAAQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAABQBZAugCA4QgBA1hcA+IgDABIgBAAg");
	this.shape_13.setTransform(63,24.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_4}]},1).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_7}]},1).to({state:[{t:this.shape_8}]},1).to({state:[{t:this.shape_9}]},1).to({state:[{t:this.shape_10}]},1).to({state:[{t:this.shape_11}]},1).to({state:[{t:this.shape_12}]},1).to({state:[{t:this.shape_13}]},1).wait(6));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.envelopeclosedstatic = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.Bitmap10();
	this.instance.setTransform(-39.6,-26.1);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-39.6,-26.1,82,52);


(lib.arrow2 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AhPA7IBPh1IBQB1g");
	this.shape.setTransform(8,2.1);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,-3.9,16.1,12);


(lib.movie_2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		/* stop();*/
	}
	this.frame_214 = function() {
		/* stop();*/
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(214).call(this.frame_214).wait(1));

	// arrows
	this.instance = new lib.arrow2("synched",0);
	this.instance.setTransform(469.3,76.8,0.538,0.538,90,0,0,7.9,2);

	this.instance_1 = new lib.arrow2("synched",0);
	this.instance_1.setTransform(568,76.8,0.538,0.538,90,0,0,7.9,2);

	this.instance_2 = new lib.arrow2("synched",0);
	this.instance_2.setTransform(379.9,76.8,0.538,0.538,90,0,0,7.9,2);

	this.instance_3 = new lib.arrow2("synched",0);
	this.instance_3.setTransform(285.3,76.8,0.538,0.538,90,0,0,7.9,2);

	this.instance_4 = new lib.arrow2("synched",0);
	this.instance_4.setTransform(195,76.8,0.538,0.538,90,0,0,7.9,2);

	this.instance_5 = new lib.arrow2("synched",0);
	this.instance_5.setTransform(112.5,76.8,0.538,0.538,90,0,0,7.9,2.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_5},{t:this.instance_4},{t:this.instance_3},{t:this.instance_2},{t:this.instance_1},{t:this.instance}]}).wait(215));

	// lazytext
	this.instance_6 = new lib.Symbol17();
	this.instance_6.setTransform(610.9,58.5,1,1,0,0,0,40,8.5);

	this.instance_7 = new lib.Symbol16();
	this.instance_7.setTransform(517.5,58.5,1,1,0,0,0,40,8.5);

	this.instance_8 = new lib.Symbol15();
	this.instance_8.setTransform(153.9,58.5,1,1,0,0,0,40,8.5);

	this.instance_9 = new lib.Symbol14();
	this.instance_9.setTransform(70,58.5,1,1,0,0,0,40,8.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_9},{t:this.instance_8},{t:this.instance_7},{t:this.instance_6}]}).wait(215));

	// text7
	this.instance_10 = new lib.Symbol26();
	this.instance_10.setTransform(610.9,76.9,1,1,0,0,0,35,8.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(215));

	// text6
	this.instance_11 = new lib.Symbol25();
	this.instance_11.setTransform(518.5,76.9,1,1,0,0,0,41.2,8.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(215));

	// text5
	this.instance_12 = new lib.Symbol24();
	this.instance_12.setTransform(424,76.9,1,1,0,0,0,38,8.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(215));

	// text4
	this.instance_13 = new lib.Symbol23();
	this.instance_13.setTransform(331.5,76.9,1,1,0,0,0,40.1,8.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_13).wait(215));

	// text3
	this.instance_14 = new lib.Symbol22();
	this.instance_14.setTransform(239.3,76.9,1,1,0,0,0,37.5,8.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_14).wait(215));

	// text2
	this.instance_15 = new lib.Symbol21();
	this.instance_15.setTransform(153.9,76.9,1,1,0,0,0,33.5,8.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_15).wait(215));

	// text1
	this.instance_16 = new lib.Symbol20();
	this.instance_16.setTransform(69.5,76.9,1,1,0,0,0,34.4,8.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_16).wait(215));

	// camera light
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF0000").s().p("AgOAOQgGgGAAgIQAAgHAGgGQAHgHAHAAQAIAAAGAHQAHAGAAAHQAAAIgHAGQgGAHgIAAQgHAAgHgHg");
	this.shape.setTransform(221,184.7);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(14).to({_off:false},0).to({_off:true},2).wait(2).to({_off:false},0).to({_off:true},2).wait(2).to({_off:false},0).to({_off:true},2).wait(2).to({_off:false},0).to({_off:true},7).wait(182));

	// computer 2 screen
	this.instance_17 = new lib.Bitmap7();
	this.instance_17.setTransform(433.2,305.4);

	this.instance_18 = new lib.Bitmap9();
	this.instance_18.setTransform(433.2,305.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_17}]}).to({state:[{t:this.instance_17}]},152).to({state:[{t:this.instance_18}]},9).wait(54));

	// computer 2
	this.instance_19 = new lib.Bitmap6();
	this.instance_19.setTransform(420.8,298.9);

	this.timeline.addTween(cjs.Tween.get(this.instance_19).wait(215));

	// envelope
	this.instance_20 = new lib.envelopeclosedstatic();
	this.instance_20.setTransform(226.8,209.8,0.36,0.36,0,0,0,18.8,21.6);
	this.instance_20.alpha = 0;
	this.instance_20._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_20).wait(56).to({_off:false},0).to({alpha:1},5).to({x:459.6,y:315.9},65).wait(89));

	// computer1 screen
	this.instance_21 = new lib.Bitmap8();
	this.instance_21.setTransform(197.9,191);

	this.instance_22 = new lib.Bitmap9();
	this.instance_22.setTransform(197.9,191);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_21}]}).to({state:[{t:this.instance_21}]},33).to({state:[{t:this.instance_22}]},5).wait(177));

	// computer 1
	this.instance_23 = new lib.Bitmap5();
	this.instance_23.setTransform(185.7,179.8);

	this.timeline.addTween(cjs.Tween.get(this.instance_23).wait(215));

	// labels2
	this.instance_24 = new lib.Symbol18();
	this.instance_24.setTransform(218,256.3,1,1,0,0,0,68,8.5);
	this.instance_24.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_24).wait(14).to({alpha:1},0).wait(112).to({alpha:0},0).wait(89));

	// labels1
	this.instance_25 = new lib.Symbol19();
	this.instance_25.setTransform(455.2,371.2,1,1,0,0,0,71.8,8.5);
	this.instance_25.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_25).wait(126).to({alpha:1},0).wait(89));

	// line
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#010000").ss(2,1,1).p("Ay1pQMAlrASh");
	this.shape_1.setTransform(323.2,246.2);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(215));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(30,50,705.6,333);


(lib.movie_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		/* stop();*/
	}
	this.frame_214 = function() {
		/* stop();*/
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(214).call(this.frame_214).wait(1));

	// arrows
	this.instance = new lib.arrow2("synched",0);
	this.instance.setTransform(469.3,76.8,0.538,0.538,90,0,0,7.9,2);

	this.instance_1 = new lib.arrow2("synched",0);
	this.instance_1.setTransform(568,76.8,0.538,0.538,90,0,0,7.9,2);

	this.instance_2 = new lib.arrow2("synched",0);
	this.instance_2.setTransform(379.9,76.8,0.538,0.538,90,0,0,7.9,2);

	this.instance_3 = new lib.arrow2("synched",0);
	this.instance_3.setTransform(285.3,76.8,0.538,0.538,90,0,0,7.9,2);

	this.instance_4 = new lib.arrow2("synched",0);
	this.instance_4.setTransform(195,76.8,0.538,0.538,90,0,0,7.9,2);

	this.instance_5 = new lib.arrow2("synched",0);
	this.instance_5.setTransform(112.5,76.8,0.538,0.538,90,0,0,7.9,2.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_5},{t:this.instance_4},{t:this.instance_3},{t:this.instance_2},{t:this.instance_1},{t:this.instance}]}).wait(215));

	// lazytext
	this.instance_6 = new lib.Symbol4();
	this.instance_6.setTransform(610.9,58.5,1,1,0,0,0,40,8.5);

	this.instance_7 = new lib.Symbol3();
	this.instance_7.setTransform(517.5,58.5,1,1,0,0,0,40,8.5);

	this.instance_8 = new lib.Symbol2();
	this.instance_8.setTransform(153.9,58.5,1,1,0,0,0,40,8.5);

	this.instance_9 = new lib.Symbol1();
	this.instance_9.setTransform(70,58.5,1,1,0,0,0,40,8.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_9},{t:this.instance_8},{t:this.instance_7},{t:this.instance_6}]}).wait(215));

	// text7
	this.instance_10 = new lib.Symbol11();
	this.instance_10.setTransform(610.9,76.9,1,1,0,0,0,35,8.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(215));

	// text6
	this.instance_11 = new lib.Symbol10();
	this.instance_11.setTransform(518.5,76.9,1,1,0,0,0,41.2,8.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(215));

	// text5
	this.instance_12 = new lib.Symbol9();
	this.instance_12.setTransform(424,76.9,1,1,0,0,0,38,8.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(215));

	// text4
	this.instance_13 = new lib.Symbol8();
	this.instance_13.setTransform(331.5,76.9,1,1,0,0,0,40.1,8.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_13).wait(215));

	// text3
	this.instance_14 = new lib.Symbol7();
	this.instance_14.setTransform(239.3,76.9,1,1,0,0,0,37.5,8.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_14).wait(215));

	// text2
	this.instance_15 = new lib.Symbol6();
	this.instance_15.setTransform(153.9,76.9,1,1,0,0,0,33.5,8.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_15).wait(215));

	// text1
	this.instance_16 = new lib.Symbol5();
	this.instance_16.setTransform(69.5,76.9,1,1,0,0,0,34.4,8.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_16).wait(215));

	// text woman
	this.instance_17 = new lib.Symbol12();
	this.instance_17.setTransform(218.2,427,1,1,0,0,0,68,8.5);
	this.instance_17.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_17).wait(9).to({alpha:1},0).wait(206));

	// text man
	this.instance_18 = new lib.Symbol13();
	this.instance_18.setTransform(441.7,427,1,1,0,0,0,68,8.5);
	this.instance_18.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_18).wait(183).to({alpha:1},0).wait(32));

	// people
	this.instance_19 = new lib.Bitmap4();
	this.instance_19.setTransform(375.6,199);

	this.instance_20 = new lib.Bitmap3();
	this.instance_20.setTransform(171.7,195.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_20},{t:this.instance_19}]}).wait(215));

	// Layer 5
	this.instance_21 = new lib.signalpulse();
	this.instance_21.setTransform(270.9,218.8);
	this.instance_21._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_21).wait(24).to({_off:false},0).to({_off:true},133).wait(58));

	// Layer 7
	this.instance_22 = new lib.Bitmap1();
	this.instance_22.setTransform(413.5,119);

	this.instance_23 = new lib.Bitmap2();
	this.instance_23.setTransform(413.5,119);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.instance_22}]},9).to({state:[{t:this.instance_22}]},162).to({state:[{t:this.instance_23}]},12).wait(32));

	// Layer 8
	this.instance_24 = new lib.Bitmap2();
	this.instance_24.setTransform(173.3,119);
	this.instance_24._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_24).wait(9).to({_off:false},0).wait(206));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(30,50,705.6,388.9);


(lib.slide_2 = function() {
	this.initialize();

	// anim2
	this.anim2 = new lib.movie_2();
	this.anim2.setTransform(318.4,157,1,1,0,0,0,318.4,157);

	this.addChild(this.anim2);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(30,50,705.6,332.9);


(lib.slide_1 = function() {
	this.initialize();

	// anim1
	this.anim1 = new lib.movie_1();
	this.anim1.setTransform(347.9,279.5,1,1,0,0,0,347.9,279.6);

	this.addChild(this.anim1);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(30,50,705.6,388.7);


(lib.Main = function() {
	this.initialize();

	// slide2
	this.slide02 = new lib.slide_2();
	this.slide02.setTransform(202.5,126.5,1,1,0,0,0,202.5,126.5);

	// slide1
	this.slide01 = new lib.slide_1();
	this.slide01.setTransform(202.5,126.5,1,1,0,0,0,202.5,126.5);

	this.addChild(this.slide01,this.slide02);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(30,50,705.6,388.7);


// stage content:
(lib.media_3113 = function() {
	this.initialize();

	// main
	this.instance = new lib.Main();

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(370,295,705.6,388.7);

})(lib = lib||{}, images = images||{}, createjs = createjs||{});
var lib, images, createjs;